site_name: TPSIT Quinta
site_url: https://tpsit-an.github.io/tpsit-quinta/
site_description: Dispense scolastiche - Quinta

theme:
  name: material
  language: it
  palette:
    scheme: slate
    primary: teal
    accent: amber
  font:
    text: JetBrains Mono
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.prune
    - navigation.indexes
    - navigation.path
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.footnote.tooltips
    - navigation.top
    - search.suggest
    - search.highlight
  icon:
    admonition:
      note: octicons/tag-16

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - abbr

extra:
  mermaid:
    theme: dark

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/mermaid.mjs
  - javascripts/highlight-lines.js

nav:
  - Home: index.md
  - Thread, Socket e HTTP:
    - Introduzione: big-picture/index.md
    - Thread - Linea di esecuzione:
      - Linea di esecuzione: big-picture/linea/1.linea.md
      - "Prevedibilità della linea di esecuzione": big-picture/linea/2.prevedibilità.md
      - I thread e la linea di esecuzione: big-picture/linea/3.linea_thread.md
      - Linee di esecuzione multiple: big-picture/linea/4.Linee di esecuzione multiple.md
      - Legenda: big-picture/linea/legenda.md
    - Socket - Operazioni I/O:
      - Linea di esecuzione bloccata: big-picture/io/0.bloccata.md
      - "connect e accept": big-picture/io/1.connect e accept.md
      - "send e recv": big-picture/io/2.send e recv.md
    # - Client-Server:
    #   - "OneToOne": big-picture/client-server/one2one.md
    #   - "ManyToOne": big-picture/client-server/many2one.md
  # - Architettura client-server:
  #   - Tiers: client-server/index.md
  # - HTTP:
  #   - http/index.md
  #   - HTTP dettaglio: http/http.md
